# Generated by Django 5.1.1 on 2024-10-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_about_objectiveabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='countryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageCountry', models.ImageField(upload_to='contList')),
                ('nameCountry', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='enquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiryName', models.CharField(max_length=200)),
                ('enquiryEmail', models.EmailField(max_length=254)),
                ('enquiryPhone', models.IntegerField()),
                ('enquiryProfession', models.CharField(max_length=200)),
                ('enquirySubject', models.CharField(max_length=300)),
                ('enquiryMessage', models.TextField()),
            ],
        ),
    ]
