# Generated by Django 5.1.1 on 2024-10-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_countrylist_enquiryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='japanAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutJapan', models.TextField()),
                ('aboutjapanImg', models.ImageField(upload_to='japanAboutimg')),
            ],
        ),
        migrations.CreateModel(
            name='japanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificationJapan', models.ImageField(upload_to='japanDoc')),
                ('japanDocName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='japanProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanProcessImg', models.ImageField(upload_to='jpnPro')),
                ('japanProcessDetail', models.TextField()),
            ],
        ),
    ]
