# Generated by Django 5.1.1 on 2024-10-28 05:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_documentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japanabout',
            name='aboutJapan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
